### ISSUE TITLE
Download script URL 404

### ISSUE THREAD

**Issue by JiDai** [ViBiOh/deploy#105]
Hi,

In the readme you specified the URL to download directly the deploy script. But this URL return a 404 error :

```
https://raw.githubusercontent.com/ViBiOh/deploy/main/deploy
```

Which URL should I use ?
Thanks

**Comment by ViBiOh** [comment]
Hi @JiDai 

It's now an embed script: when the binary starts, it copies the script in the current folder. The script is [here](https://github.com/ViBiOh/deploy/blob/main/pkg/api/scripts/deploy-compose). I'll update the README 👍
